config/routes.rb
RbfProj::Application.routes.draw do
  get "savingsdeposittransactions/index"
  get "savingsdeposittransactions/new"
  get "savingsdeposittransactions/create"
  get "savingsdeposittransactions/show"
  get "savingsdeposittransactions/pending"
  get "savingsdeposittransactions/activate"

  get "savingsdeposits/new"
  get "savingsdeposits/create"
  get "savingsdeposits/show"
  get "savingsdeposits/pending"
  get "savingsdeposits/activate"
 
resources :savingsdeposits do
   get :autocomplete_customer_first_name, :on => :collection
   get :approve, :on => :member
   put :activate, :on => :member
end

#match "savingsdeposits/:id/activate" => "savingsdeposits#activate", :as => "active_savingsdeposit"
  get "folios/index"
  resources :folios

resources :savingsdeposittransactions do
   put :activate, :on => :member
  end

resources :dailyproducts
  get "dailyproducts/show"
  
devise_for :users, :controllers => { :registrations =>'registration'}

resources :customers

resources :home
  get 'dashboard' => 'home#dashboard'
  get "home/show"
  
root :to =>'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

 def index
  #@user = current_user
 end

 def show
  @user = current_user
 end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/dashboard.html.erb
<style>
#header {display:none;}
#footer {display:none;}
</style>

<div class="offset3 span6">
<h2>Successfully Registered...</h2>
<h2>You need to signin now</h2>
<br><%= link_to "Sign In", new_user_session_path, :method => :get,class: "btn btn-primary" %></br>
</div>

app/views/home/index.html.erb
<style>
#header {display:none;}
#footer {display:none;}

 .carousel-inner > .item > img,
 .carousel-inner > .item > a > img {
 display: block;
 max-width: 100%;
 height: 300px !important;
 }
</style>

<script>
$(function(){
  $('#myCarousel').carousel();
});
</script>

<% if user_signed_in? %>
<br></br>
<h2><%= link_to "Click here to list all customers", customers_path%></h2>
<br><br/>
<h2>click here to see/edit user details</h2> 
<h2><%= link_to "user profile",home_show_path,class: "btn btn-primary" %></h2>

<% else %>
  <div class = "span3 offset3" align="center">
    <h1>Ruby Benefit Fund</h1>
  </div>

<br /> <br />


<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>


  <div class="carousel-inner">
     <div class="item active">
      <%= image_tag 'coin.jpg' %>
     </div>
    
     <div class="item">
      <%= image_tag 'deposit.jpg' %>
     </div>

     <div class="item">
      <%= image_tag 'umb.png' %>
     </div>
  </div>

 
  <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
    <span class="sr-only">Previous</span>
  </a>
  
  <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>
<br /><br /><br />

<h5 align="center"><b>You need to sign in or sign up before continouning!! </b></h5>
<div class = "span3 offset3" align="center">
<%= link_to "Sign In", new_user_session_path, :method => :get, :class => "btn btn-info" %>
<%= link_to "Sign up", new_user_registration_path, :method => :get, :class => "btn btn-info" %>
</div>
<% end %>

app/views/home/show.html.erb
<br /> 

   <div class="span6 customer_left_span_properties">
   <h4><span class="customer">User details</span></h4><br /> 

   <strong>USER NAME</strong> - <%= @user.username %>   
   <br></br>

   <strong>EMAIL-ID</strong>
   - <%= @user.email %>
   
   <br></br>

   <strong>MOBILE</strong>
   - <%= @user.mobile_number %>
   <br></br>

   <strong>ADDRESS</strong>
  - <%= @user.Address %> 
   
   <br></br>

   <strong>LOGIN COUNT</strong>
   - <%= @user.sign_in_count %> 
   <br></br>

<%= link_to "Edit",edit_user_registration_path,class: "btn btn-primary" %>
<%= link_to "Back",home_index_path,class: "btn btn-primary" %>