config/routes.rb
RbfProj::Application.routes.draw do
  get "savingsdeposittransactions/index"
  get "savingsdeposittransactions/new"
  get "savingsdeposittransactions/create"
  get "savingsdeposittransactions/show"
  get "savingsdeposittransactions/pending"
  get "savingsdeposittransactions/activate"

  get "savingsdeposits/new"
  get "savingsdeposits/create"
  get "savingsdeposits/show"
  get "savingsdeposits/pending"
  get "savingsdeposits/activate"
 
resources :savingsdeposits do
   get :autocomplete_customer_first_name, :on => :collection
   get :approve, :on => :member
   put :activate, :on => :member
end

#match "savingsdeposits/:id/activate" => "savingsdeposits#activate", :as => "active_savingsdeposit"
  get "folios/index"
  resources :folios

resources :savingsdeposittransactions do
   put :activate, :on => :member
  end

resources :dailyproducts
  get "dailyproducts/show"
  
devise_for :users, :controllers => { :registrations =>'registration'}

resources :customers

resources :home
  get 'dashboard' => 'home#dashboard'
  get "home/show"
  
root :to =>'home#index'
end

app/models/customer.rb
# == Schema Information
#
# Table name: customers
#
#  id            :integer          not null, primary key
#  first_name    :string(255)
#  last_name     :string(255)
#  date_of_birth :date
#  sex           :string(255)
#  address       :text
#  city          :string(255)
#  state         :string(255)
#  pincode       :integer
#  PAN           :text
#  status        :string(255)
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Customer < ActiveRecord::Base
has_many :folios
accepts_nested_attributes_for :folios

has_many :savingsdeposits
accepts_nested_attributes_for :savingsdeposits


attr_accessible :code, :PAN, :address, :city, :date_of_birth, :first_name, :last_name, :pincode, :sex, :state, :status, :photo, :folios_attributes, :savingsdeposits_attributes
belongs_to :user 
mount_uploader :photo, PhotoUploader 



before_create :increment_code
def increment_code
    self.code = (self.class.last.nil?) ? "0000000001" : ((self.class.last.code.to_i) + 1).to_s.rjust(10,'0')
end

before_save :set_default_val
def set_default_val
   self.status = 'Pending' unless self.status
end




validates :first_name, presence: true,
		       format: { with: %r{\A[a-zA-Z]*} }
validates :last_name, presence: true,
		      format: { with: %r{\A[a-zA-Z]*} }

validates_numericality_of :pincode, presence: true
validates_length_of :pincode, :is => 6, :wrong_length => "should have 6digits"

validates :PAN, presence: true, format: { with: %r{\A[A-Z]{5}\d{4}[A-Z]{1}} }
validates_length_of :PAN, :is => 10, :wrong_length => "should have 10digits"
validates_uniqueness_of :PAN 

validates_inclusion_of :date_of_birth,
                :in => Date.civil(1900,1,1)..Date.today,
                 :message => "is invalid"

#validates_uniqueness_of :code, presence: true, :wrong_length => "should have 10digits"
#validates_length_of :code, :is =>10, :start_code => 0000000001
#validates :code, numericality: { greater_than_or_equal_to: 0000000001 }

validates :address, presence: true
validates :sex, presence: true
validates :state, presence: true
validates :city, presence: true
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

 
 def new
  @customer = Customer.new
  @folio = @customer.folios.build
  @savingsdeposit = @customer.savingsdeposits.build
 end

 def create
  @customer = Customer.new(params[:customer])
    if @customer.save
       flash.keep[:success] = "Welcome!"
       redirect_to customer_path(@customer)           
    else
       flash.keep[:alert] = "Customer not added"
       render 'new'
    end    
 end

 def index
  @customers = Customer.all
  @customers = Customer.where("first_name LIKE ? OR code LIKE ?", "%#{params[:search]}%", "%#{params[:search]}%").paginate(page: params[:page], per_page: 5)
 end 

 def edit
  @customer = Customer.find(params[:id])
 end

 def update
  @customer = Customer.find(params[:id])
    if @customer.update_attributes(params[:customer])
       flash.keep[:success] = "updated successfully"
       redirect_to customers_path(@customer)
    else
       flash.keep[:alert] = "failed"
       render 'edit'
    end
 end

 def show
  @customer = Customer.find(params[:id])
 end
 
 def destroy
  @customer = Customer.find(params[:id])
  @customer.destroy
   flash.keep[:notice] = "customer has been deleted"
   redirect_to customers_path
 end


end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/views/customers/_form.html.erb
<br />
<div class="row">
    <div class="span6 offset3">
    <%= form_for(@customer) do |f| %>
    <% if @customer.errors.any? %>
    <h4>customer could not be added:</h4>
    <ul> <% @customer.errors.full_messages.each do |error|%>
    <li><%= error%></li>
    <% end%>
    </ul>
<% end%>
    

     <%= f.label :first_name %>
     <%= f.text_field :first_name %>

     <%= f.label :last_name %>
     <%= f.text_field :last_name %>
 
     <%= f.label :photo %>
     <%= f.file_field :photo %>
     
     <%= f.label :date_of_birth %>
     <%= f.text_field :date_of_birth %>
    
     <%= f.label :sex %>
     <%= f.radio_button :sex, "male" %>
     <%= f.label :sex, "male", :value => "male" %>
     <%= f.radio_button :sex, "female" %>
     <%= f.label :sex, "female", :value => "female" %>
     
     <%= f.label :Address %>
     <%= f.text_area :address, :id => "address", :cols =>3, :rows =>3 %>

     <%= f.label :city %>
     <%= f.text_field :city %>
  
     <%= f.label :state %>
     <%= f.text_field :state %>

     <%= f.label :pincode %>
     <%= f.text_field :pincode %>
 
     <%= f.label :PAN %>
     <%= f.text_field :PAN %>

     <!--<%= f.label :status %>
     <%= submit_tag "pending", :type => 'button', :value => "pending" %>--> 

   <br><br> <%= f.submit "submit", class: "btn btn-large btn-primary" %> </br></br>
    <% end %>
  </div>
</div>

app/views/customers/edit.html.erb
<br/>
<h1>Edit customer</h1>
 
 <%= form_for @customer, :html => {:multipart => true} do |f| %>
  <% if @customer.errors.any? %>
 <section id="flashMsg">
<div class="alert alert-block alert-error"> <a class="close" data-dismiss="alert" href="#">X</a> <h4 class="alert-heading">Error!</h4> updation failed </div>  </section>
  <ul>
  <% @customer.errors.full_messages.each do |error| %>
  <li><%= error %></li>
  <% end %>
  </ul>
 <% end %>

<h4><span class="customer">Customer details</span></h4>     
<%= f.label :code %>
<%= f.text_field :code,:readonly => true %><br />

<%= f.label :first_name %>
<%= f.text_field :first_name %><br />

<%= f.label :last_name %>
<%= f.text_field :last_name %><br />

<%= f.label :date_of_birth %>
<%= f.text_field :date_of_birth %><br />

<%= f.label :sex %><br />
<%= f.radio_button :sex, "male" %>
     <%= f.label :sex, "male", :value => "male" %><br />
     <%= f.radio_button :sex, "female" %>
     <%= f.label :sex, "female", :value => "female" %><br />
 
<hr>
<h4><span class="customer">Contact details</span></h4>
  
<%= f.label :city %>
<%= f.text_field :city %><br />

<%= f.label :state %>
<%= f.text_field :state %><br />

<%= f.label :pincode %>
<%= f.text_field :pincode %><br />

<%= f.label :address %>
<%= f.text_field :address, :id => "address", :cols => 5, :rows => 3 %><br />
</hr>

<hr>
  <h4><span class="customer">ID details</span></h4>
  <%= f.label :PAN %>
  <%= f.text_field :PAN %>
</hr>

<hr>
  <h4><span class="customer">Photo</span></h4>
  <%= f.label :Photo %>
  <%= f.file_field :photo %>
</hr> 

<br />          
<fieldset class="form-actions"> <%= f.submit "Update Customer", class: "btn btn-primary" %></field>
<% end %>

app/views/customers/index.html.erb
<h1> Customers </h1>

<%= form_tag customers_path, :method => 'get', :class => "form-search" do %>
  <%= text_field_tag :search, nil, :placeholder => "name or code", 
      :class => "input-medium search-query" %>
  <%= submit_tag "Find!", :name => nil, :class => "btn btn-primary" %>
  <%= link_to "New customer", new_customer_path,class: "btn btn-primary" %>
<% end %>


<h6 class= "alert alert-info"><%= page_entries_info @customers %></h6>

<div> <table cellpadding = "5px" cellspacing = "5px" width = "100%" class="table table-striped">
 
  <tr>
    <th>FOLIO NUMBER</th>
    <th>CODE</th>
    <th>NAME</th>
    <th>ADDRESS</th>
    <th>PHOTO</th>
    <th> E/D</th>
  </tr>

  <% @customers.each do |customer| %>

    <tr>
      <td><% for folio in customer.folios %><%= link_to folio.folio_number, folios_path %><% end %></td>
      <td><%= link_to "#{customer.code}" , customer_path(customer)%></td>
      <td><%= link_to "#{customer.first_name} #{customer.last_name}" , customer_path(customer)%>   <td><%= customer.address%></td>
      <td><%= image_tag customer.photo, :size => "50x50" , class:"img-polaroid" %></td>
      <td><%= link_to "Edit",edit_customer_path(customer),class: "btn btn-success" %>
      <%= link_to "Delete",customer_path(customer),class: "btn btn-danger",
      method: :destroy_all, data: {confirm: "Are You Sure?"} %></td>
  <% end %>
 </tr>
</table>

<%= will_paginate @customers %>
</div>

app/views/customers/index.js.erb
jQuery('#customers').html(" 'customers/customers' )%>");
$('.pagination a').attr('data-remote', 'true');

app/views/customers/new.html.erb
<br />
<h1>New customer</h1>


 <%= form_for @customer, :html => {:multipart => true} do |f| %>
  <% if @customer.errors.any? %>  
  <ul>
  <% @customer.errors.full_messages.each do |error| %>
  <li><%= error %></li>
  <% end %>
  </ul>
 <% end %>



<h4><span class="customer">Customer details</span></h4>     

<%= f.label :first_name ,class: 'required'%>
<%= f.text_field :first_name %><br />

<%= f.label :last_name ,class: 'required'%>
<%= f.text_field :last_name %><br />

<%= f.label :date_of_birth ,class: 'required' %>
<%= f.text_field :date_of_birth %><br />

<%= f.label :sex ,class: 'required' %> <br />
<%= f.radio_button :sex, "male" %>
    <%= f.label :sex, "male", :value => "male" %><br />
     <%= f.radio_button :sex, "female" %>
     <%= f.label :sex, "female", :value => "female" %><br />
   
<hr>
<h4><span class="customer">Contact details</span></h4>
 
<%= f.label :city, class: 'required' %>
<%= f.text_field :city %><br />

<%= f.label :state, class: 'required' %>
<%= f.text_field :state %><br />

<%= f.label :pincode, class: 'required' %>
<%= f.text_field :pincode %><br />

<%= f.label :address ,class: 'required' %>
<%= f.text_field :address, :id => "address", :cols => 5, :rows => 3 %><br />
</hr>

<hr>
 <h4><span class="customer">ID details</span></h4>
     <%= f.label :PAN ,class: 'required'%>
     <%= f.text_field :PAN %>
</hr>

<hr>
<h4><span class="customer">Photo</span></h4>
<%= f.label :Photo %>
<%= f.file_field :photo %>
</hr> 

<hr>
  <%= f.fields_for :folios do |f|%>
  <h4><span class="customer">Share</span></h4>
      <%= f.label :no_of_shares ,class: 'required'%>
      <%= f.text_field :no_of_shares, :class => 'textbox', :value => '' %>
  <% end %>
</hr> 
<br /><br />
          
<fieldset class="form-actions"> <%= f.submit "Create Customer", class: "btn btn-primary" %></field>
<% end %>
</div>
</div>

app/views/customers/show.html.erb
<br />
<h1><%= link_to "Customers", customers_path %></h1>  
<br />

<div id="customer" align="right"> 
   <div class="btn-group">

    <a class="btn btn-primary" href="/customers">
       <span class="glyphicon glyphicon-user"></span> List all Customers</a>

    <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#">
       <span class="caret"></span></a>
       
   <ul class="dropdown-menu">
    <li><%= link_to(edit_customer_path(@customer)) do %>
      Edit Current Customer <span class="glyphicon glyphicon-pencil"></span>
    <% end %></li>
  
   </div>
</div>

   <h4><span class = "customer"><%= @customer.code %></span></h4>
       <%= "#{@customer.first_name} #{@customer.last_name}" %>
   <h5><%= "Age : #{Date.today.year - @customer.date_of_birth.year}" %></h5> 
   <h5><%= @customer.address %></h5>

 <hr>
   <h4><span class="customer">APPLICATION DETAILS</span></h4>

   <!--<h5>Status : <%= @customer.status %> </h5>-->

   <h5>Folio number: <% for folio in @customer.folios %><%= link_to folio.folio_number, folios_path %>   <% end %> </h5>

   <h5>Number of shares: <% for folio in @customer.folios %>                                     <%= link_to folio.no_of_shares, folios_path %><% end %></h5>
 </hr>

 <hr>   
   <h4><span class="customer">PHOTO</span></h4> 
   <h5><%= image_tag @customer.photo, :size => "50x50", :crop => :fill %></h5>
 </hr>

 <hr>   
   <h4><span class="customer">CUSTOMER DETAILS</span></h4>
   <h5>Date of birth: <%= @customer.date_of_birth %></h5>
   <h5>Gender: <%= @customer.sex %></h5>
 </hr>

 <hr>  
   <h4><span class="customer">ID DETAILS</span></h4>
   <h5>PAN: <%= @customer.PAN %> </div></h5>
 </hr>

<br></br>

<div class = "span3 offset3">
  <a class="btn btn-info btn-lg btn-block" href="/customers">Back</a>
</div>