config/routes.rb
RbfProj::Application.routes.draw do
  get "savingsdeposittransactions/index"
  get "savingsdeposittransactions/new"
  get "savingsdeposittransactions/create"
  get "savingsdeposittransactions/show"
  get "savingsdeposittransactions/pending"
  get "savingsdeposittransactions/activate"

  get "savingsdeposits/new"
  get "savingsdeposits/create"
  get "savingsdeposits/show"
  get "savingsdeposits/pending"
  get "savingsdeposits/activate"
 
resources :savingsdeposits do
   get :autocomplete_customer_first_name, :on => :collection
   get :approve, :on => :member
   put :activate, :on => :member
end

#match "savingsdeposits/:id/activate" => "savingsdeposits#activate", :as => "active_savingsdeposit"
  get "folios/index"
  resources :folios

resources :savingsdeposittransactions do
   put :activate, :on => :member
  end

resources :dailyproducts
  get "dailyproducts/show"
  
devise_for :users, :controllers => { :registrations =>'registration'}

resources :customers

resources :home
  get 'dashboard' => 'home#dashboard'
  get "home/show"
  
root :to =>'home#index'
end

app/controllers/savingsdeposittransactions_controller.rb
class SavingsdeposittransactionsController < ApplicationController

 def index
   @savingsdeposittransactions = Savingsdeposittransaction.all
  end

 def new
   @savingsdeposittransaction = Savingsdeposittransaction.new
   @savingsdeposittransaction.savingsdeposit_id = params[:id]
 end

 def pending
   @savingsdeposittransaction = Savingsdeposittransaction.all
 end

 def approve
   @savingsdeposittransaction = Savingsdeposittransaction.find(params[:id])
 end

 def create
  @savingsdeposittransaction = Savingsdeposittransaction.new(params[:savingsdeposittransaction])
   if @savingsdeposittransaction.save
     flash.keep[:success] = "Savingsdeposittransaction added!"
     redirect_to savingsdeposits_path
    else
     flash.keep[:alert] = "savingsdeposittransaction not added"
     render 'new'
   end    
 end

 def edit
   @savingsdeposittransaction = Savingsdeposittransaction.find(params[:id])
 end

 def update
  @savingsdeposittransaction = Savingsdeposittransaction.find(params[:id])
   if @savingsdeposittransaction.update_attributes(params[:savingsdeposittransaction])
      flash.keep[:success] = "updated successfully"
      redirect_to savingsdeposittransaction_path(@savingsdeposittransaction)
    else
      flash.keep[:alert] = "failed"
      render 'edit'
   end
 end

 def show
       #@savingsdeposittransaction = current.savingsdeposittransaction
  @savingsdeposittransaction = Savingsdeposittransaction.find(params[:id])
  @customer = Customer.all
 end
 
 def destroy
  @savingsdeposittransaction = Savingsdeposittransaction.find(params[:id])
  @savingsdeposittransaction.destroy
  flash.keep[:notice] = "savingsdeposittransaction has been deleted"
  redirect_to savingsdeposittransaction_path
 end

 def activate
  @savingsdeposittransaction = Savingsdeposittransaction.find(params[:id])
  @savingsdeposittransaction.update_attributes!(:status => 'approved')
  redirect_to savingsdeposittransaction_path(@savingsdeposittransaction)
 end 

end

app/helpers/savingsdeposittransactions_helper.rb
module SavingsdeposittransactionsHelper
end

app/views/savingsdeposittransactions/approve.html.erb
<h1><span class="savingsdeposit">Savingsdeposit details</span></h1><br /><br />
<div class="row">
 <div class="span6 offset6 action_bar">
  <div>
  <%= link_to "Edit transaction", edit_savingsdeposit_path(:id => @savingsdeposit.id),class: "btn-primary btn" %>
  <%= link_to "Add transaction", new_savingsdeposittransaction_path(:id => @savingsdeposit.id),class: "btn-primary btn" %>
  </div>
 </div></div>
 
<h5><%= "#{@savingsdeposit.customer.first_name} #{@savingsdeposit.customer.last_name}               #{@savingsdeposit.customer.code}" %></h5>

<table cellpadding = "5px" cellspacing = "5px" width = "100%" class="table table-striped">
<tr>
     <th>opened on</th>
      <th>status</th>
      <th>Account type</th>
      <th>current balance</th>
</tr>
 
<tr>
    <td><%= @savingsdeposit.opened_on %></td>
    <td><%= @savingsdeposit.status %></td> 
    <td><%= @savingsdeposit.account_type %></td> 
    <td><%= @savingsdeposit.current_balance %></td>
</tr>
</table>

<h1>Transaction History</h1><br />
<table cellpadding = "5px" cellspacing = "5px" width = "100%" class="table table-striped">
<tr>
      <th>transaction date</th>
      <th>transaction type</th>
      <th>transaction mode</th>
      <th>transaction amount</th>
      <th>particulars</th>
      <th>status</th>
</tr>
<% @savingsdeposit.savingsdeposittransactions.each do |f|%>
<tr>
    <td><%= f.transaction_date %></td>
    <td><%= f.transaction_type %></td>
    <td><%= f.transaction_mode %></td>
    <td><%= f.transaction_amount %></td>
    <td><%= f.particulars %></td> 
    <td><%= f.status %></td> 
</tr>
<% end %>
</table>


  <%= form_for @savingsdeposit, url: activate_savingsdeposit_path(@savingsdeposit), :html => { :method => :put } do |f| %>
  <%= f.submit "approve record", class: "btn btn-danger"  %>
   <% end %>

<div align = "right">
<a class="btn btn-inverse" href="/dailyproducts">Daily Product</a>
</div>

app/views/savingsdeposittransactions/new.html.erb
<h1><span class="customer">Savings Deposit</span></h1>
<h3><span class="customer"> New Transaction</span> </h3>

<%= form_for @savingsdeposittransaction do |f| %>
   <%= f.hidden_field :savingsdeposit_id , :value => params[:id] %>
    <% if @savingsdeposittransaction.errors.any? %>
       <h4>savingsdeposittransaction not added</h4>
    <ul>
       <% @savingsdeposittransaction.errors.full_messages.each do |error| %>
       <li><%= error %></li>
       <% end %>
    </ul>
<% end %>

<%= f.label :transaction_date %>
<%= f.text_field :transaction_date, :value => Date.today, :readonly => true %><br />

<%= f.label :transaction_type %> 
<%= f.select(:transaction_type, options_for_select(['cash','bank'])) %><br />


<% if @savingsdeposittransaction.transaction_type == 'bank' %>
  <%= f.label :bank %> 
<%= f.select(:transaction_type, options_for_select(['cub','icici'])) %><br />

<% end %>


<%= f.label :current_balance %>
<%= f.text_field :current_balance, :value => @savingsdeposittransaction.savingsdeposit.current_balance, :readonly => true %><br />
   
<%= f.label :transaction_mode %>
<%= f.select(:transaction_mode, options_for_select([['Credit', 'Credit'], ['Debit', 'Debit']]))%><br />

<%= f.label :transaction_amount %>
<%= f.text_field :transaction_amount %><br />

<%= f.label :comments %>
<%= f.text_field :particulars, :id => "particulars" %><br />
<br />
<br />

<fieldset class="form-actions"> 
<%= f.submit "Add Transaction", class: "btn btn-primary" %></field>
<% end %>

app/views/savingsdeposittransactions/pending.html.erb
<br /><h1> Pending Savingsdeposittransactions</h1><br />

<table cellpadding = "5px" cellspacing = "5px" width = "100%" class="table table-striped">
<tr>
      <th>savingsdeposit id</th>
      <th>transaction type</th>
      <th>transaction mode</th>
      <th>transaction amount</th>
      <th>status</th>
</tr>
<% @savingsdeposittransaction.each do |f|%>
<tr>
      <td><%= f.savingsdeposit_id %></td>
    <td><%= f.transaction_type %></td>
    <td><%=link_to"#{f.transaction_mode}", savingsdeposittransaction_path(f) %></td>
    <td><%= f.transaction_amount %></td>
    <td><%= f.status %></td> 
</tr>
<% end %>
</table>

app/views/savingsdeposittransactions/show.html.erb
<h1>Savingsdeposit Transaction<h1>
<% if can? :approve,@savingsdeposittransaction %>
<%= form_for @savingsdeposittransaction, url: activate_savingsdeposittransaction_path(@savingsdeposittransaction), :html => {:method => :put} do |f| %>
<%= f.submit "approve", class: "btn-btn danger" %>
<% end %><% end %>
<h5><table cellpadding = "5px" cellspacing = "5px" width = "100%" class="table table-striped">
<tr>
      <th>savingsdeposit id</th>
      <th>transaction date</th>
      <th>transaction type</th>
      <th>transaction mode</th>
      <th>transaction amount</th>
      <th>particulars</th>
      <th>status</th>
</tr>

<tr>
      <td><%= @savingsdeposittransaction.savingsdeposit_id %></td>
    <td><%= @savingsdeposittransaction.transaction_date %></td>
    <td><%= @savingsdeposittransaction.transaction_type %></td>
    <td><%= @savingsdeposittransaction.transaction_mode %></td>
    <td><%= @savingsdeposittransaction.transaction_amount %></td>
    <td><%= @savingsdeposittransaction.particulars %></td> 
    <td><%= @savingsdeposittransaction.status %></td> 
</tr>

</table></h5>