config/routes.rb
RbfProj::Application.routes.draw do
  get "savingsdeposittransactions/index"
  get "savingsdeposittransactions/new"
  get "savingsdeposittransactions/create"
  get "savingsdeposittransactions/show"
  get "savingsdeposittransactions/pending"
  get "savingsdeposittransactions/activate"

  get "savingsdeposits/new"
  get "savingsdeposits/create"
  get "savingsdeposits/show"
  get "savingsdeposits/pending"
  get "savingsdeposits/activate"
 
resources :savingsdeposits do
   get :autocomplete_customer_first_name, :on => :collection
   get :approve, :on => :member
   put :activate, :on => :member
end

#match "savingsdeposits/:id/activate" => "savingsdeposits#activate", :as => "active_savingsdeposit"
  get "folios/index"
  resources :folios

resources :savingsdeposittransactions do
   put :activate, :on => :member
  end

resources :dailyproducts
  get "dailyproducts/show"
  
devise_for :users, :controllers => { :registrations =>'registration'}

resources :customers

resources :home
  get 'dashboard' => 'home#dashboard'
  get "home/show"
  
root :to =>'home#index'
end

app/models/savingsdeposit.rb
class Savingsdeposit < ActiveRecord::Base

belongs_to :customer
    
has_many :savingsdeposittransactions

has_many :dailyproducts

#belongs_to  :user

#before_filter :authenticate_user!

accepts_nested_attributes_for :savingsdeposittransactions

#attr_accessor :total_bal
attr_accessor :transaction_amount
attr_accessible :savingsdeposittransactions_attributes

attr_accessor :first_name
attr_accessible :first_name
attr_accessible :account_type, :current_balance, :opened_on, :status, :customer_id



before_save :set_default_val
  def set_default_val
            self.status = 'Pending' unless self.status
  end


before_save :set_opened_on_date
 def set_opened_on_date
    self.opened_on = Date.today
 end

  validates :customer_id, presence: true
  validates :account_type, presence: true
  validates :current_balance, presence: true
  validates_numericality_of :current_balance, :greater_than_or_equal_to => 100
 
end

app/controllers/savingsdeposits_controller.rb
class SavingsdepositsController < ApplicationController

 autocomplete  :customer, :first_name, :display_value => :first_name, :full => true
 
 def index
   @savingsdeposits = Savingsdeposit.all
 end

 def pending
   @savingsdeposits = Savingsdeposit.all
 end

 def approve
   @savingsdeposit = Savingsdeposit.find(params[:id])
 end

 def new
   @savingsdeposit = Savingsdeposit.new
 end

 def create
   @savingsdeposit = Savingsdeposit.new(params[:savingsdeposit])
    if @savingsdeposit.save 
      flash.keep[:success] = "sd added!"
      redirect_to savingsdeposits_path          
     else
      flash.keep[:alert] = "SD not added"
      render 'new'
    end    
 end

 def show
  @savingsdeposit = Savingsdeposit.find(params[:id])
  @customer = Customer.all
  @savingsdeposittransactions = Savingsdeposittransaction.all
 end

 def edit
  @savingsdeposit = Savingsdeposit.find(params[:id])
 end

 def update
  @savingsdeposit = Savingsdeposit.find(params[:id])
    if @savingsdeposit.update_attributes(params[:savingsdeposit])
       flash.keep[:success] = "Profile updated successfully"
       redirect_to savingsdeposits_path(@savingsdeposit)
    else
       flash.keep[:error] = "Cannot updating your profile"
       render 'edit'
    end
 end

 def activate
  @savingsdeposit = Savingsdeposit.find(params[:id])
  @savingsdeposit.update_attributes!(:status => 'approved')
  redirect_to approve_savingsdeposit_path(@savingsdeposit)
  end 
end

app/helpers/savingsdeposits_helper.rb
module SavingsdepositsHelper
end

app/views/savingsdeposits/approve.html.erb
<h1><span class="savingsdeposit">Savingsdeposit details</span></h1><br /><br />
<div class="row">
 <div class="span6 offset6 action_bar">
  <div>
  <%= link_to "Edit transaction", edit_savingsdeposit_path(:id => @savingsdeposit.id),class: "btn-primary btn" %>
  <%= link_to "Add transaction", new_savingsdeposittransaction_path(:id => @savingsdeposit.id),class: "btn-primary btn" %><br /><br />

  <%= form_for @savingsdeposit, url: activate_savingsdeposit_path(@savingsdeposit), :html => { :method => :put } do |f| %>
  <%= f.submit "approve savingsdeposit", class: "btn btn-danger"  %>
   <% end %>
  </div>
 </div></div>
 
<h5><%= "#{@savingsdeposit.customer.first_name} #{@savingsdeposit.customer.last_name}               #{@savingsdeposit.customer.code}" %></h5>

<table cellpadding = "5px" cellspacing = "5px" width = "100%" class="table table-striped">
<tr>
     <th>opened on</th>
      <th>status</th>
      <th>Account type</th>
      <th>current balance</th>
</tr>
 
<tr>
    <td><%= @savingsdeposit.opened_on %></td>
    <td><%= @savingsdeposit.status %></td> 
    <td><%= @savingsdeposit.account_type %></td> 
    <td><%= @savingsdeposit.current_balance %></td>
</tr>
</table>

<h1>Transaction History</h1><br />
<table cellpadding = "5px" cellspacing = "5px" width = "100%" class="table table-striped">
<tr>
      <th>transaction date</th>
      <th>transaction type</th>
      <th>transaction mode</th>
      <th>transaction amount</th>
      <th>particulars</th>
      <th>status</th>
</tr>
<% @savingsdeposit.savingsdeposittransactions.each do |f|%>
<tr>
    <td><%= f.transaction_date %></td>
    <td><%= f.transaction_type %></td>
    <td><%= f.transaction_mode %></td>
    <td><%= f.transaction_amount %></td>
    <td><%= f.particulars %></td> 
    <td><%= f.status %></td> 
</tr>
<% end %>
</table>



<div align = "right">
<a class="btn btn-inverse" href="/dailyproducts">Daily Product</a>
</div>

app/views/savingsdeposits/edit.html.erb
<h2><span class="customer">Edit Account</span></h2><br />
<h5><span class="customer"><%= "#{@savingsdeposit.customer.first_name} #{@savingsdeposit.customer.last_name}               #{@savingsdeposit.customer.code}" %></h5>
</span>
<br />
 <%= form_for @savingsdeposit do |f| %>

 
    <% if @savingsdeposit.errors.any? %>
  <h4>Customer not added</h4>
  <ul>
  <% @savingsdeposit.errors.full_messages.each do |error| %>
  <li><%= error %></li>
  <% end %>
  </ul>
 <% end %>
 
 
 <%= f.label :current_balance %>
 <%= f.text_field :current_balance, :readonly => true %><br />
 
<%= f.label :opened_on %>
 <%= f.text_field :opened_on, :readonly => true, :value => @savingsdeposit.opened_on %><br />

 <%= f.label :account_type %> 
 <%= f.text_field :account_type %><br /><br />

 <fieldset class="form-actions"> <%= f.submit "update account", class: "btn btn-primary" %></field>
 <% end %></div>

app/views/savingsdeposits/index.html.erb
<br />
<h1> <span class="customer">Savings deposit</span></h1>
  <br />
     <%= link_to "New savings deposits", new_savingsdeposit_path,class: "btn-primary btn" %>

<div class="btn-group">
      <a class="btn btn-primary">Transactions Pending</a>
      <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#">
      <span class="caret"></span></a>
       <ul class="dropdown-menu">
    <% if current_user.role == "manager"%>
        <li> <%= link_to 'Awaiting Approval',savingsdeposits_pending_path(@savingsdeposit)%></li>
     <% end %>

        </ul>
   </div>
     </div>
   <br />
<br>
<table cellpadding = "5px" cellspacing = "5px" width = "100%" class="table table-striped">
  <tr>
    <th>ID</th>
    <th>CURRENT BALANCE</th>
    <th>OPENED ON</th>
    <th>ACCOUNT TYPE</th>
    <th>STATUS</th>
    <th>DETAILS</th>

 </tr>
    <% @savingsdeposits.each do |savingsdeposit| %>
      <tr>
      <td><%= savingsdeposit.customer_id %></td>
      <td><%= savingsdeposit.current_balance %></td>
      <td><%= savingsdeposit.opened_on %></td>
      <td><%= savingsdeposit.account_type %></td>
      <td><span class="label label-success"><%= savingsdeposit.status %><%= @pending %>
</span></td>
      <td> <% if current_user.role == "manager"%>
        <li> <%= link_to 'Awaiting Approval',savingsdeposits_pending_path(@savingsdeposit)%></li>
     <% end %>
<%= link_to(savingsdeposit_path(savingsdeposit), :class => 'btn btn-small btn-info') do %>
More info <i class="icon-info-sign icon-white"></i>
                   <% end %>
</td>
      </tr>
    <% end %>
  </table>
 </div>

app/views/savingsdeposits/new.html.erb
<h1><span class="customer">New Savingsdeposit</span></h1>

 <%= form_for @savingsdeposit do |f| %>
   <% if @savingsdeposit.errors.any? %>
      <h4>Customer not added</h4>
        <ul>
          <% @savingsdeposit.errors.full_messages.each do |error| %>
          <li><%= error %></li>
          <% end %>
        </ul>
 <% end %>

<br /><br />

    <%= f.hidden_field :customer_id, :id => "real_customer_id" %>
    <%= f.label :customer_name %>
    <%= autocomplete_field_tag 'throwaway_customer', '',
          autocomplete_customer_first_name_savingsdeposits_path,
          :size => 25, :id_element => '#real_customer_id' %> <br /> <br />
 
    
    <%= f.label :current_balance %>
    <%= f.text_field :current_balance, :value =>"0.00" %><br /> <br />

    <%= f.label :opened_on, class: 'required' %>
    <%= f.text_field :opened_on,  :value => Time.now.strftime("%m/%d/%Y"), :readonly => true%><br /><br />

    <%= f.label :account_type %>
    <%= f.text_field :account_type %><br />
    <br /> <br />

<fieldset class="form-actions"> <%= f.submit "open account", class: "btn btn-primary" %></field>
<% end %></div>

app/views/savingsdeposits/pending.html.erb
<br />
<h1><span class="customer"> Pending records</span></h1>
  <br />

     <table cellpadding = "5px" cellspacing = "5px" width = "100%" class="table table-striped">
  <tr>
    <th>customer id</th>
    <th>current balance</th>
    <th>opened on</th>
    <th>status</th>
    <th>Account type</th>

 </tr>

    <% @savingsdeposits.each do |savingsdeposit| %>

<% if savingsdeposit.status == "Pending" %>
      <tr>
      <td><%= savingsdeposit.customer_id %></td>
      <td><%= savingsdeposit.current_balance %></td>
      <td><%= savingsdeposit.opened_on %></td>
      <td><span class="label label-warning"><%= savingsdeposit.status %></span></td>
      <td><%= link_to "#{savingsdeposit.account_type}", approve_savingsdeposit_path(savingsdeposit) %>
      </td>
      
</tr>
    <% end %> 
<% end %> 
 </table>

app/views/savingsdeposits/show.html.erb
<h1><span class="customer">Savingsdeposit details</span></h1><br /><br />

<div id="customer" align="right"> 
 <%= link_to "Edit transaction", edit_savingsdeposit_path,class: "btn-primary btn" %>

<% if @savingsdeposit.status == 'approved' %>
  <%= link_to "Add transaction", new_savingsdeposittransaction_path(:id=>@savingsdeposit.id),class: "btn-primary btn" %>
<% end %></div>


<h3><span class="customer"><%= "#{@savingsdeposit.customer.first_name} #{@savingsdeposit.customer.last_name}               #{@savingsdeposit.customer.code}" %></span></h3><br />

<table cellpadding = "5px" cellspacing = "5px" width = "100%" class="table table-striped">
   <tr>
      <th>opened on</th>
      <th>status</th>
      <th>Account type</th>
      <th>current balance</th>
   </tr>
 
   <tr>
      <td><%= @savingsdeposit.opened_on %></td>
      <td><%= @savingsdeposit.status %></td> 
      <td><%= @savingsdeposit.account_type %></td> 
      <td><%= @savingsdeposit.current_balance %></td>
   </tr>
</table>
<br />
<h1><span class="customer">Transaction History</span></h1>
</div>

   <div id="customer" align="right"> 
      <%= link_to 'Pending Transaction',savingsdeposittransactions_pending_path(@savingsdeposittransaction),class: "btn-primary btn"%><br /><br />
   </div>

<table cellpadding = "3px" cellspacing = "3px" width = "100%" class="table table-striped">
   <tr>
      <th>transaction date</th>
      <th>transaction type</th>
      <th>transaction mode</th>
      <th>transaction amount</th>
      <th>particulars</th>
      <th>status</th>
   </tr>

   <% @savingsdeposit.savingsdeposittransactions.each do |f|%>

   <tr>
      <td><%= f.transaction_date %></td>
      <td><%= f.transaction_type %></td>
      <td><%= f.transaction_mode %></td>
      <td><%= f.transaction_amount %></td>
      <td><%= f.particulars %></td> 
      <td><%= f.status %></td> 
   </tr>
  
   <% end %>

</table>